version: '3'
services:
  django:
    container_name: django_admin
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000

  pgdb:
    image: postgres:13-alpine
    container_name: my_pg_13
    env_file:
      - config/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h $${DB_HOST} -U $${DB_USER} -d $${DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.19.2
    container_name: my-nginx
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/configs:/etc/nginx/conf.d:ro
      - ./static:/data/static
    depends_on:
      - django
    ports:
      - "8000:80"
#  etl:
#    image: python:3.8
#    depends_on:
#      pgdb:
#        condition: service_healthy
#    build:
#      context: etl
#      dockerfile: Dockerfile
